name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  shared_preferences: ^2.0.15
  fl_chart: ^0.64.0
  firebase_storage: ^12.4.5
  image_picker: ^0.8.4+5
  csv: ^5.0.2
  path_provider: ^2.1.2
  url_launcher: ^6.3.1
  firebase_messaging: ^15.2.5

  intl: ^0.20.2
  permission_handler: ^11.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: android\Assetss\Icon\IMG.png  
  min_sdk_android: 21



  
